# @package _global_

hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    params:
      exp.loss_type: erm
      exp.tol: -1.2
      exp.loss_alpha: 0.0
      exp.dual_step_size: 0.1

  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

  sweep:
    dir: ./multirun
    subdir: ${hydra.job.num}

train:
  seed: 42
  output_dir: "./outputs/safe/${exp.loss_type}/alpha:${exp.loss_alpha}-tol:${exp.tol}-lr:${exp.dual_step_size}"
  do_train: true
  do_initial_eval: true
  use_wandb: true
  save_model: false
  wandb_project: "SAFE-final-v2"
  run_name: "run-alpha:${exp.loss_alpha}-tol:${exp.tol}-lr:${exp.dual_step_size}"
  eval_on_train: false
  enable_profiler: false
  include_inputs_for_metrics: true
  dropout: 0.0
  data_proportion: 1.0
  eval_frac: 0.1
  filter_longest: true
  only_unsafe_train: true
  only_unsafe_eval: true
  max_length: 2048
  eval_at_end: true
  lora:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.1
  hf_args:
    per_device_train_batch_size: 1          # ST recipe
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 64
    eval_accumulation_steps: 8
    num_train_epochs: 15                      # ST example uses 1 epoch
    learning_rate: 1e-5
    lr_scheduler_type: "linear"
    warmup_ratio: 0.0
    weight_decay: 0.0
    gradient_checkpointing: false
    load_best_model_at_end: false
    eval_strategy: "epoch"
    save_strategy: "epoch"
    # metric_for_best_model: "objective"
    # greater_is_better: true
    # save_total_limit: 1
    eval_do_concat_batches: false
    bf16: true
    fp16: false

exp:
  name: "safety"
  model_name: huggyllama/llama-7b
  loss_type: aug_dual
  tol: -1.2
  loss_alpha: 3
  dual_step_size: 0.1
