# @package _global_

# hydra:
#   mode: MULTIRUN
#   sweeper:
#     _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
#     params:
#       exp.loss_type: penalty
#       exp.tol: 1
      
#   launcher:
#     _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

#   sweep:
#     dir: ./multirun
#     subdir: ${hydra.job.num}

train:
  seed: 42
  cuda_visible_devices: "0"
  output_dir: "./outputs/safe/${exp.loss_type}/alpha:${exp.loss_alpha}-tol:${exp.tol}-lr:${exp.dual_step_size}"
  do_train: true
  do_initial_eval: false
  use_wandb: true
  wandb_project: "SAFE-lima"
  eval_every_n_epochs: 5
  run_name: "run-alpha:${exp.loss_alpha}-tol:${exp.tol}-lr:${exp.dual_step_size}"
  eval_on_train: true
  enable_profiler: false
  include_inputs_for_metrics: true
  # If != 1.0, enable constraint-aware resampling:
  # examples with safe==True (constraints) get this sampling weight, others get weight 1.0.
  constraint_weighted_sampler_weight: 8.0
  dropout: 0.0
  data_proportion: 1.0
  max_length: 512
  lora:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.05
  hf_args:
    per_device_train_batch_size: 2          # ST recipe
    per_device_eval_batch_size: 2
    gradient_accumulation_steps: 64
    eval_accumulation_steps: 16
    num_train_epochs: 15                      # ST example uses 1 epoch
    learning_rate: 1e-4
    lr_scheduler_type: "cosine"
    warmup_ratio: 0.01
    weight_decay: 0.001
    eval_strategy: "epoch"
    save_strategy: "epoch"
    gradient_checkpointing: false
    load_best_model_at_end: true
    metric_for_best_model: "objective"
    greater_is_better: true
    save_total_limit: 1
    eval_do_concat_batches: false
    bf16: true
    fp16: false

exp:
  name: "safety"
  model_name: huggyllama/llama-7b
  loss_type: aug_dual
  tol: -0.1
  loss_alpha: 10
  dual_step_size: 1.0