# @package _global_

hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    params:
      exp.loss_type: penalty
      exp.loss_alpha: 20
      exp.tol2: 0.0
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

  sweep:
    dir: ./multirun
    subdir: ${hydra.job.num}

train:
  seed: 42
  output_dir: "./outputs/safe/${exp.loss_type}/alpha:${exp.loss_alpha}-tol:${exp.tol}-lr:${exp.dual_step_size}"
  do_train: true
  do_initial_eval: false
  use_wandb: true
  save_model: true
  wandb_project: "SAFE-long1k"
  run_name: "run-alpha:${exp.loss_alpha}-tol:${exp.tol}-lr:${exp.dual_step_size}"
  eval_on_train: true
  enable_profiler: false
  include_inputs_for_metrics: true
  dropout: 0.0
  data_proportion: 1.0
  # Optional: cap number of prompts for train-end generation/logprob eval. Disabled by default.
  max_gen: null
  max_length: 2048
  eval_at_end: true
  filter_longest: true
  only_unsafe_train: false
  only_unsafe_eval: false
  push_adapters_to_wandb: true
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
  hf_args:
    per_device_train_batch_size: 4          # ST recipe
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 8
    eval_accumulation_steps: 4
    num_train_epochs: 10                      # ST example uses 1 epoch
    learning_rate: 5e-4
    lr_scheduler_type: "cosine"
    warmup_ratio: 0.1
    weight_decay: 0.01
    eval_strategy: "no"
    save_strategy: "no"
    gradient_checkpointing: false
    # load_best_model_at_end: true
    # metric_for_best_model: "objective"
    # greater_is_better: true
    # save_total_limit: 1
    eval_do_concat_batches: false
    bf16: true
    fp16: false

exp:
  name: "safety"
  model_name: ihounie/huggy-2-1k-alpaca-f16
  dataset: ihounie/SAFE-ALPACA-BTails-llama2
  loss_type: penalty
  tol: 0.0
  tol2: -0.0
  loss_alpha: 10
  dual_step_size: 0
