# @package _global_

hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    params:
      exp.loss_type: penalty
      exp.loss_alpha: 0.001, 0.0001

  # Ensure sequential launching (no parallel launcher)
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

  # Optional: get deterministic per-job folders 0,1,2,...
  sweep:
    dir: ./multirun
    subdir: ${hydra.job.num}  # 0,1,2,... in the iteration order


train:
  seed: 42
  output_dir: "outputs/bias/${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.ratio}-${exp.tol}"
  do_train: true
  do_initial_eval: false
  use_wandb: true
  include_inputs_for_metrics: true
  wandb_project: "BIAS-final-v2"
  run_name: "bias-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.ratio}-${exp.tol}"
  eval_on_train: false
  enable_profiler: false
  dropout: 0.2
  data_proportion: 1.0
  size: small
  eval_train_at_end: true
  eval_at_end: true
  hf_args:
    per_device_train_batch_size: 16          # ST recipe
    per_device_eval_batch_size: 16
    gradient_accumulation_steps: 4
    num_train_epochs: 5                      # ST example uses 1 epoch
    learning_rate: 5e-5
    warmup_ratio: 0.1
    weight_decay: 0.03
    lr_scheduler_type: "linear"
    eval_strategy: "no"
    save_strategy: "no"
    # save_total_limit: 1
    bf16: true
    fp16: false

exp:
  name: "bias"
  loss_alpha: 10
  loss_type: penalty
  model_name: microsoft/deberta-v3-base
  ratio: fair # Options: "fair", "ones"
  tol: 0.02
  dual_step_size: 1
  resilient_coef: 1.0