# @package _global_

# hydra:
#   mode: MULTIRUN
#   sweeper:
#     _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
#     params:
#       exp.tol: 0.02
#       exp.loss_alpha: 3,100
#       exp.loss_type: l2

#   # Ensure sequential launching (no parallel launcher)
#   launcher:
#     _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

#   # Optional: get deterministic per-job folders 0,1,2,...
#   sweep:
#     dir: ./multirun
#     subdir: ${hydra.job.num}  # 0,1,2,... in the iteration order

train:
  seed: 42
  output_dir: "./outputs/safe/run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.tol}"
  do_train: true
  do_initial_eval: true
  log_tables: true
  use_wandb: true
  wandb_project: "SAFE-debugging"
  run_name: "run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.tol}"
  data_proportion: 0.05
  eval_on_train: true
  enable_profiler: true
  lora:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.05
  profiler:
    wait: 99
    warmup: 0
    active: 1
    repeat: 9999
    output_dir: "log/safe/${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.tol}/"
  hf_args:
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 8
    num_train_epochs: 4
    learning_rate: 5e-6
    lr_scheduler_type: "linear"
    warmup_ratio: 0.1
    weight_decay: 0.01
    eval_strategy: "epoch"
    save_strategy: "epoch"
    gradient_checkpointing: true
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    greater_is_better: true
    save_total_limit: 1
    fp16: true
exp:
  name: "safety"
  model_name: huggyllama/llama-7b
  loss_type: penalty
  tol: 0.0
  loss_alpha: 1000
